- hosts: ubuntu
  connection: local
  tasks:
    - name: install nvidia-driver
      apt:
        pkg:
          - ubuntu-drivers-common
          - nvidia-driver-440
    - name: install nvidia-container-toolkit 2
      script: /home/ubuntu/git/BrokenArrow/ansible/scripts/setup-nvctoolkit.sh