- hosts: ubuntu
  connection: local
  tasks:
    - name: download docker
      apt: 
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
    - name: install docker
      script: /home/ubuntu/BrokenArrow/ansible/scripts/install-docker.sh
    - name: install docker-compose
      apt:
        pkg:
          - docker-compose