- hosts: ubuntu
  connection: local
  tasks:
    - name: install nvidia-driver
      apt:
        pkg:
          - ubuntu-drivers-common
          - nvidia-utils-460-server # ubuntu20.04.1
    - name: install nvidia-container-toolkit 2
      script: /home/ubuntu/BrokenArrow/ansible/scripts/setup-nvctoolkit.sh